name: Build Docker image
on:
  push: {}
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # bake-action does not yet load .env
      - name: Export .env to environment variables
        run: export $(cat .env | grep -v "#" | xargs)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/bake-action@v2.0.0
        with:
          push: false
          load: true
          set: |
            test.cache-from=type=gha
            test.cache-to=type=gha
      
      - name: Test
        run: docker compose run test